apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp2-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cp2-cluster
  template:
    metadata:
      labels:
        app: cp2-cluster
    spec:
      containers:
      - name: cp2-cluster
        image: localhost:32000/primenum:v1
        ports:
        - containerPort: 80
