apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-deployment
  template:
    metadata:
      labels:
        app: fastapi-deployment
    spec:
      containers:
      - name: fastapi-deployment
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-lb
spec:
  type: LoadBalancer
  selector:
    app: fastapi-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80